name: 'Docker Registry Tag'
description: 'Add many tags to an image in a Docker Registry (retag, re-tag)'
author: 'Theia Scientific, LLC'
inputs:
  registry:
    description: 'Registry API root domain'
    required: true
  token:
    description: 'Bearer token for the Registry API'
    required: true
    default: '${{ github.token }}'
  package:
    description: 'Package name'
    required: true
  target:
    description: 'Target Tag'
    required: true
  tags:
    description: 'New-line separated list of new tags'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'blue'
