name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  registry: ghcr.io
  package: '${{ github.repository }}'
  tag: 'test-${{ github.run_id }}'
  image: 'ghcr.io/theia-scientific/update-registry-tag:test-${{ github.run_id }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and test action
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: '${{ env.registry }}'
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add example image to container registry for test repository
        run: |
          docker pull hello-world
          docker tag hello-world ${{ env.image }}
          docker push ${{ env.image }}

      - name: Add One Tag
        uses: ./
        with:
          registry: '${{ env.registry }}'
          package: '${{ env.package }}'
          target: '${{ env.tag }}'
          tags: '${{ env.tag }}-single'

      - name: Add Multiple Tags
        uses: ./
        with:
          registry: '${{ env.registry }}'
          package: '${{ env.package }}'
          target: '${{ env.tag }}'
          tags: |
            ${{ env.tag }}-multiple-a
            ${{ env.tag }}-multiple-b
